# Site settings
title: Zihan's Notebook
email: 904323606@qq.com
description: > # this means to ignore newlines until "baseurl:"
  If you love my works, please scan this QR-Code by wechat to follow me. Or you could leave me a short message through contact. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zihan.design" # the base hostname & protocol for your site
weibo_name: snakeshawn
weichat_name: Zihan随身本
twitter_username: snakeshawn
github_username: snakeshawn

# Build settings
markdown: kramdown
permalink: pretty
