# Site settings
title: Zihan's Sketchbook
email: zihan_nku@126.com
description: > # this means to ignore newlines until "baseurl:"
  This is Zihan's sketch book, my personal online page. This gallery mainly contains my recent illustration works. If you want to know more about my art works or work with me, please contact me.
statement: > # this means to ignore newlines until "baseurl:"
  Please scan the QR code in Wechat to follow my subscription. Or you could leave me a short message through contact. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zihan.design" # the base hostname & protocol for your site

assets_url: "http://zihan.design/PUB/./public/database/zihan.design/assets"

weibo_name: zihancircus
weichat_name: galars
twitter_username: snakeshawn
github_username: snakeshawn

# Build settings
markdown: kramdown
permalink: pretty
